name: cogni_sarthi
description: CogniSarthi - AI-Powered File Analysis Chatbot
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  file_picker: ^8.0.0+1
  http: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
